version: '2'

services:

wordpress:
    image: travisaustin/wordpress:latest
    volumes:
        - ./html:/var/www/html
    ports:
        - 81:80
    restart: always
    environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: ${MYSQL_USER:-wordpress}
        WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
        WORDPRESS_DB_DATABASE: ${MYSQL_DATABASE:-wordpress}

  db:
    image: mariadb:10.3
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wordpress}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

#  adminer:
#    image: adminer
#    ports:
#      - 82:8080
#    environment:
#      ADMINER_DEFAULT_SERVER: 'db'
#    depends_on:
#      - db
#    mem_limit: 350m

#  ubuntu:
#    build:
#      dockerfile: ubuntu/Dockerfile
#      context: .
#    volumes_from:
#      - wordpress
#    volumes:
#      - ./backups:/backups

volumes:
  db_data: